let gifFiles= [
    './interfaz/imagenes/Cards/Monsters/1 - m5sEQkS.gif',
    './interfaz/imagenes/Cards/Monsters/10 - vXt2UVx.gif',
    './interfaz/imagenes/Cards/Monsters/11 - v7tfdmb.gif',
    './interfaz/imagenes/Cards/Monsters/12 - KDERk1h.gif',
    './interfaz/imagenes/Cards/Monsters/13 - nTYATdN.gif',
    './interfaz/imagenes/Cards/Monsters/14 - XMZMLg0.gif',
    './interfaz/imagenes/Cards/Monsters/15 - B6DGYw2.gif',
    './interfaz/imagenes/Cards/Monsters/16 - pefquWa.gif',
    './interfaz/imagenes/Cards/Monsters/17 - HCtZRfg.gif',
    './interfaz/imagenes/Cards/Monsters/18 - 3U5I30l.gif',
    './interfaz/imagenes/Cards/Monsters/19 - 4ufDucK.gif',
    './interfaz/imagenes/Cards/Monsters/2 - QSmhcSe.gif',
    './interfaz/imagenes/Cards/Monsters/20 - AbZvJtD.gif',
    './interfaz/imagenes/Cards/Monsters/21 - BaM7q1h.gif',
    './interfaz/imagenes/Cards/Monsters/22 - 5cBlGkw.gif',
    './interfaz/imagenes/Cards/Monsters/23 - 25Ggddg.gif',
    './interfaz/imagenes/Cards/Monsters/24 - x4lzI56.gif',
    './interfaz/imagenes/Cards/Monsters/25 - Gje88Vs.gif',
    './interfaz/imagenes/Cards/Monsters/26 - RGfbjMD.gif',
    './interfaz/imagenes/Cards/Monsters/27 - 8wL16k7.gif',
    './interfaz/imagenes/Cards/Monsters/28 - 4MnVC4i.gif',
    './interfaz/imagenes/Cards/Monsters/29 - xHj7nU2.gif',
    './interfaz/imagenes/Cards/Monsters/3 - Z1CLU9H.gif',
    './interfaz/imagenes/Cards/Monsters/30 - iAq8qwi.gif',
    './interfaz/imagenes/Cards/Monsters/31 - icIw0Jt.gif',
    './interfaz/imagenes/Cards/Monsters/32 - KjJ4PPd.gif',
    './interfaz/imagenes/Cards/Monsters/33 - JR4uNUG.gif',
    './interfaz/imagenes/Cards/Monsters/34 - KjsTQvj.gif',
    './interfaz/imagenes/Cards/Monsters/35 - aSCzvOS.gif',
    './interfaz/imagenes/Cards/Monsters/36 - Y7hdwZV.gif',
    './interfaz/imagenes/Cards/Monsters/37 - cyt5Cxn.gif',
    './interfaz/imagenes/Cards/Monsters/38 - UvnizlM.gif',
    './interfaz/imagenes/Cards/Monsters/39 - a8I35fd.gif',
    './interfaz/imagenes/Cards/Monsters/4 - Mga8mcU.gif',
    './interfaz/imagenes/Cards/Monsters/40 - ELhwbnr.gif',
    './interfaz/imagenes/Cards/Monsters/41 - qwAoBrU.gif',
    './interfaz/imagenes/Cards/Monsters/42 - Z0WTCwH.gif',
    './interfaz/imagenes/Cards/Monsters/43 - q9NEfv1.gif',
    './interfaz/imagenes/Cards/Monsters/44 - OnW9bUB.gif',
    './interfaz/imagenes/Cards/Monsters/45 - bgKfrk6.gif',
    './interfaz/imagenes/Cards/Monsters/46 - SuVwC9W.gif',
    './interfaz/imagenes/Cards/Monsters/47 - iXGzlK3.gif',
    './interfaz/imagenes/Cards/Monsters/48 - Hv1QrBb.gif',
    './interfaz/imagenes/Cards/Monsters/49 - F3PXIbN.gif',
    './interfaz/imagenes/Cards/Monsters/5 - mS2OwAN.gif',
    './interfaz/imagenes/Cards/Monsters/50 - gKeARqD.gif',
    './interfaz/imagenes/Cards/Monsters/51 - lJkqLbP.gif',
    './interfaz/imagenes/Cards/Monsters/52 - pggmy0M.gif',
    './interfaz/imagenes/Cards/Monsters/53 - wJIgj6C.gif',
    './interfaz/imagenes/Cards/Monsters/54 - 2Y7P2Di.gif',
    './interfaz/imagenes/Cards/Monsters/55 - RblLAHM.gif',
    './interfaz/imagenes/Cards/Monsters/56 - fLRxz6A.gif',
    './interfaz/imagenes/Cards/Monsters/6 - fLtRe0d.gif',
    './interfaz/imagenes/Cards/Monsters/7 - jiAtUtn.gif',
    './interfaz/imagenes/Cards/Monsters/8 - hjqdeIV.gif',
    './interfaz/imagenes/Cards/Monsters/9 - 7zfVxNb.gif',
    './interfaz/imagenes/Cards/Neutral Cards/1 - ijV9ksZ.gif',
    './interfaz/imagenes/Cards/Neutral Cards/10 - xXEaU2a.gif',
    './interfaz/imagenes/Cards/Neutral Cards/11 - cUqLbFi.gif',
    './interfaz/imagenes/Cards/Neutral Cards/12 - HdINOv7.gif',
    './interfaz/imagenes/Cards/Neutral Cards/13 - 61BQQLa.gif',
    './interfaz/imagenes/Cards/Neutral Cards/14 - BYs02sk.gif',
    './interfaz/imagenes/Cards/Neutral Cards/15 - f2KZN9f.gif',
    './interfaz/imagenes/Cards/Neutral Cards/16 - 9XaKL2U.gif',
    './interfaz/imagenes/Cards/Neutral Cards/17 - VB1ac3V.gif',
    './interfaz/imagenes/Cards/Neutral Cards/18 - RbRYM6r.gif',
    './interfaz/imagenes/Cards/Neutral Cards/19 - LEMRKqa.gif',
    './interfaz/imagenes/Cards/Neutral Cards/2 - e1yP1zA.gif',
    './interfaz/imagenes/Cards/Neutral Cards/20 - QtQ9EQK.gif',
    './interfaz/imagenes/Cards/Neutral Cards/21 - orBkGsl.gif',
    './interfaz/imagenes/Cards/Neutral Cards/22 - LzH6I2D.gif',
    './interfaz/imagenes/Cards/Neutral Cards/23 - PoFYwAz.gif',
    './interfaz/imagenes/Cards/Neutral Cards/24 - kaVNKtM.gif',
    './interfaz/imagenes/Cards/Neutral Cards/25 - mtNQUpQ.gif',
    './interfaz/imagenes/Cards/Neutral Cards/26 - 8MkxZ98.gif',
    './interfaz/imagenes/Cards/Neutral Cards/27 - PUlTh6G.gif',
    './interfaz/imagenes/Cards/Neutral Cards/28 - bdLGEOM.gif',
    './interfaz/imagenes/Cards/Neutral Cards/29 - zuFx8Re.gif',
    './interfaz/imagenes/Cards/Neutral Cards/3 - BXuYPU0.gif',
    './interfaz/imagenes/Cards/Neutral Cards/30 - XHnrxbp.gif',
    './interfaz/imagenes/Cards/Neutral Cards/31 - zS96m0Y.gif',
    './interfaz/imagenes/Cards/Neutral Cards/32 - 4566F6X.gif',
    './interfaz/imagenes/Cards/Neutral Cards/33 - LrVPDVE.gif',
    './interfaz/imagenes/Cards/Neutral Cards/34 - 8AOh312.gif',
    './interfaz/imagenes/Cards/Neutral Cards/35 - YLOKscS.gif',
    './interfaz/imagenes/Cards/Neutral Cards/36 - Tur8v9v.gif',
    './interfaz/imagenes/Cards/Neutral Cards/37 - ukksdkT.gif',
    './interfaz/imagenes/Cards/Neutral Cards/38 - yV7Kx1e.gif',
    './interfaz/imagenes/Cards/Neutral Cards/39 - Xzgvyj8.gif',
    './interfaz/imagenes/Cards/Neutral Cards/4 - GGB8SHP.gif',
    './interfaz/imagenes/Cards/Neutral Cards/40 - DZquE4O.gif',
    './interfaz/imagenes/Cards/Neutral Cards/41 - Zt2Z5T0.gif',
    './interfaz/imagenes/Cards/Neutral Cards/42 - BmgXEJR.gif',
    './interfaz/imagenes/Cards/Neutral Cards/43 - IwKc2im.gif',
    './interfaz/imagenes/Cards/Neutral Cards/44 - 46gnPAl.gif',
    './interfaz/imagenes/Cards/Neutral Cards/45 - 8ZUpFDG.gif',
    './interfaz/imagenes/Cards/Neutral Cards/46 - chO02gB.gif',
    './interfaz/imagenes/Cards/Neutral Cards/47 - GH0HYMA.gif',
    './interfaz/imagenes/Cards/Neutral Cards/48 - 4K021xv.gif',
    './interfaz/imagenes/Cards/Neutral Cards/49 - REBUqpS.gif',
    './interfaz/imagenes/Cards/Neutral Cards/5 - t2onUgx.gif',
    './interfaz/imagenes/Cards/Neutral Cards/50 - B7vDij5.gif',
    './interfaz/imagenes/Cards/Neutral Cards/51 - AJmmIsX.gif',
    './interfaz/imagenes/Cards/Neutral Cards/52 - IuRzmN8.gif',
    './interfaz/imagenes/Cards/Neutral Cards/53 - qiJmEmx.gif',
    './interfaz/imagenes/Cards/Neutral Cards/54 - lIzYG9G.gif',
    './interfaz/imagenes/Cards/Neutral Cards/55 - imLah8H.gif',
    './interfaz/imagenes/Cards/Neutral Cards/56 - UuMX5le.gif',
    './interfaz/imagenes/Cards/Neutral Cards/57 - 7FlHmfv.gif',
    './interfaz/imagenes/Cards/Neutral Cards/58 - vE5Lm1U.gif',
    './interfaz/imagenes/Cards/Neutral Cards/59 - xLlG7ax.gif',
    './interfaz/imagenes/Cards/Neutral Cards/6 - 0Vt1s0T.gif',
    './interfaz/imagenes/Cards/Neutral Cards/60 - rFWDC70.gif',
    './interfaz/imagenes/Cards/Neutral Cards/61 - 017Y6NE.gif',
    './interfaz/imagenes/Cards/Neutral Cards/62 - p09iWKZ.gif',
    './interfaz/imagenes/Cards/Neutral Cards/63 - YWzjmGu.gif',
    './interfaz/imagenes/Cards/Neutral Cards/64 - IpNDjF0.gif',
    './interfaz/imagenes/Cards/Neutral Cards/65 - 7tbT6Ur.gif',
    './interfaz/imagenes/Cards/Neutral Cards/66 - eza3KoY.gif',
    './interfaz/imagenes/Cards/Neutral Cards/67 - rnlJWac.gif',
    './interfaz/imagenes/Cards/Neutral Cards/68 - cVRx3WC.gif',
    './interfaz/imagenes/Cards/Neutral Cards/69 - 1FszTXU.gif',
    './interfaz/imagenes/Cards/Neutral Cards/7 - MWbqmli.gif',
    './interfaz/imagenes/Cards/Neutral Cards/70 - VpgLLnA.gif',
    './interfaz/imagenes/Cards/Neutral Cards/71 - BDnzn4K.gif',
    './interfaz/imagenes/Cards/Neutral Cards/72 - kRE3NpV.gif',
    './interfaz/imagenes/Cards/Neutral Cards/73 - SulVX5b.gif',
    './interfaz/imagenes/Cards/Neutral Cards/74 - HT7NvVX.gif',
    './interfaz/imagenes/Cards/Neutral Cards/8 - WR5OZAE.gif',
    './interfaz/imagenes/Cards/Neutral Cards/9 - JNWJGN8.gif',
    './interfaz/imagenes/Cards/Nilfgaard/1 - IHPUN9Q.gif',
    './interfaz/imagenes/Cards/Nilfgaard/10 - lstfXbW.gif',
    './interfaz/imagenes/Cards/Nilfgaard/11 - u9TrS6t.gif',
    './interfaz/imagenes/Cards/Nilfgaard/12 - eA1GI4F.gif',
    './interfaz/imagenes/Cards/Nilfgaard/13 - IYW3hB8.gif',
    './interfaz/imagenes/Cards/Nilfgaard/14 - iMPhuE5.gif',
    './interfaz/imagenes/Cards/Nilfgaard/15 - 7YCQao5.gif',
    './interfaz/imagenes/Cards/Nilfgaard/16 - GN2E0dT.gif',
    './interfaz/imagenes/Cards/Nilfgaard/17 - MtLzcqK.gif',
    './interfaz/imagenes/Cards/Nilfgaard/18 - L7K9uHI.gif',
    './interfaz/imagenes/Cards/Nilfgaard/19 - PNiTB7W.gif',
    './interfaz/imagenes/Cards/Nilfgaard/2 - f1LkIrz.gif',
    './interfaz/imagenes/Cards/Nilfgaard/20 - FkeGnPz.gif',
    './interfaz/imagenes/Cards/Nilfgaard/21 - qCLhzY5.gif',
    './interfaz/imagenes/Cards/Nilfgaard/22 - suMbz9b.gif',
    './interfaz/imagenes/Cards/Nilfgaard/23 - pNYD1sL.gif',
    './interfaz/imagenes/Cards/Nilfgaard/24 - nz1aTlN.gif',
    './interfaz/imagenes/Cards/Nilfgaard/25 - gladWgF.gif',
    './interfaz/imagenes/Cards/Nilfgaard/26 - ITgVl4p.gif',
    './interfaz/imagenes/Cards/Nilfgaard/27 - uF5juKG.gif',
    './interfaz/imagenes/Cards/Nilfgaard/28 - gTIOwNS.gif',
    './interfaz/imagenes/Cards/Nilfgaard/29 - Gr1jl4r.gif',
    './interfaz/imagenes/Cards/Nilfgaard/3 - GuEhQdb.gif',
    './interfaz/imagenes/Cards/Nilfgaard/30 - nfVyyzg.gif',
    './interfaz/imagenes/Cards/Nilfgaard/31 - J0Vy1K4.gif',
    './interfaz/imagenes/Cards/Nilfgaard/32 - F4EboN1.gif',
    './interfaz/imagenes/Cards/Nilfgaard/33 - rdDqOyE.gif',
    './interfaz/imagenes/Cards/Nilfgaard/34 - K9Nf7zO.gif',
    './interfaz/imagenes/Cards/Nilfgaard/4 - Zd6poEM.gif',
    './interfaz/imagenes/Cards/Nilfgaard/5 - q2xxQFh.gif',
    './interfaz/imagenes/Cards/Nilfgaard/6 - yDX7lts.gif',
    './interfaz/imagenes/Cards/Nilfgaard/7 - DKsDJC0.gif',
    './interfaz/imagenes/Cards/Nilfgaard/8 - ecwwqdd.gif',
    './interfaz/imagenes/Cards/Nilfgaard/9 - vih4DYB.gif',
    './interfaz/imagenes/Cards/Northern Realms/1 - npI1HHY.gif',
    './interfaz/imagenes/Cards/Northern Realms/10 - wmQQMUN.gif',
    './interfaz/imagenes/Cards/Northern Realms/11 - CKVLNJ9.gif',
    './interfaz/imagenes/Cards/Northern Realms/12 - i28OB79.gif',
    './interfaz/imagenes/Cards/Northern Realms/13 - yIukIww.gif',
    './interfaz/imagenes/Cards/Northern Realms/14 - i2kq2nP.gif',
    './interfaz/imagenes/Cards/Northern Realms/15 - 7SznStq.gif',
    './interfaz/imagenes/Cards/Northern Realms/16 - NI3ePtN.gif',
    './interfaz/imagenes/Cards/Northern Realms/17 - vSY8UNw.gif',
    './interfaz/imagenes/Cards/Northern Realms/18 - szYnsbL.gif',
    './interfaz/imagenes/Cards/Northern Realms/19 - Az23Lrm.gif',
    './interfaz/imagenes/Cards/Northern Realms/2 - Iq7UBSd.gif',
    './interfaz/imagenes/Cards/Northern Realms/20 - aiiQUPZ.gif',
    './interfaz/imagenes/Cards/Northern Realms/21 - YBr1AmE.gif',
    './interfaz/imagenes/Cards/Northern Realms/22 - g5ehbWX.gif',
    './interfaz/imagenes/Cards/Northern Realms/23 - RvG5CqO.gif',
    './interfaz/imagenes/Cards/Northern Realms/24 - lNjBfP7.gif',
    './interfaz/imagenes/Cards/Northern Realms/25 - mBlDaab.gif',
    './interfaz/imagenes/Cards/Northern Realms/26 - 4uIqCwe.gif',
    './interfaz/imagenes/Cards/Northern Realms/27 - DQ7BHCf.gif',
    './interfaz/imagenes/Cards/Northern Realms/28 - DakX6Co.gif',
    './interfaz/imagenes/Cards/Northern Realms/29 - AYHVyVk.gif',
    './interfaz/imagenes/Cards/Northern Realms/3 - ZxAJW4Y.gif',
    './interfaz/imagenes/Cards/Northern Realms/30 - mX2LgVC.gif',
    './interfaz/imagenes/Cards/Northern Realms/31 - ZOvZVkL.gif',
    './interfaz/imagenes/Cards/Northern Realms/32 - bO4oNg2.gif',
    './interfaz/imagenes/Cards/Northern Realms/33 - P0vEeQ1.gif',
    './interfaz/imagenes/Cards/Northern Realms/34 - YiORE61.gif',
    './interfaz/imagenes/Cards/Northern Realms/36 - M3wwcfo.gif',
    './interfaz/imagenes/Cards/Northern Realms/4 - 3BW8z4B.gif',
    './interfaz/imagenes/Cards/Northern Realms/5 - x2v9Q7M.gif',
    './interfaz/imagenes/Cards/Northern Realms/6 - Vff3T8h.gif',
    './interfaz/imagenes/Cards/Northern Realms/7 - lCTZYfX.gif',
    './interfaz/imagenes/Cards/Northern Realms/8 - igLoLcI.gif',
    './interfaz/imagenes/Cards/Northern Realms/9 - YlxzB0Q.gif',
    './interfaz/imagenes/Cards/Scoiatael/1 - YuVCg9M.gif',
    './interfaz/imagenes/Cards/Scoiatael/10 - etGDh87.gif',
    './interfaz/imagenes/Cards/Scoiatael/11 - kKOZIZV.gif',
    './interfaz/imagenes/Cards/Scoiatael/12 - sxP1odd.gif',
    './interfaz/imagenes/Cards/Scoiatael/13 - 71EEMWJ.gif',
    './interfaz/imagenes/Cards/Scoiatael/14 - griaixz.gif',
    './interfaz/imagenes/Cards/Scoiatael/15 - MynxVgP.gif',
    './interfaz/imagenes/Cards/Scoiatael/16 - 45QneD5.gif',
    './interfaz/imagenes/Cards/Scoiatael/17 - vLE4E9R.gif',
    './interfaz/imagenes/Cards/Scoiatael/18 - Jl8C5cg.gif',
    './interfaz/imagenes/Cards/Scoiatael/19 - OERJgnW.gif',
    './interfaz/imagenes/Cards/Scoiatael/2 - 211TbYB.gif',
    './interfaz/imagenes/Cards/Scoiatael/20 - ZgniOUG.gif',
    './interfaz/imagenes/Cards/Scoiatael/21 - PzYuEdy.gif',
    './interfaz/imagenes/Cards/Scoiatael/22 - xaIqtBj.gif',
    './interfaz/imagenes/Cards/Scoiatael/23 - SnzjchT.gif',
    './interfaz/imagenes/Cards/Scoiatael/24 - blJhIdv.gif',
    './interfaz/imagenes/Cards/Scoiatael/25 - TNNCjRU.gif',
    './interfaz/imagenes/Cards/Scoiatael/26 - zomWQ0S.gif',
    './interfaz/imagenes/Cards/Scoiatael/27 - W9H2ywB.gif',
    './interfaz/imagenes/Cards/Scoiatael/28 - qBkmJej.gif',
    './interfaz/imagenes/Cards/Scoiatael/29 - jBDxkUj.gif',
    './interfaz/imagenes/Cards/Scoiatael/3 - 7bJKsR7.gif',
    './interfaz/imagenes/Cards/Scoiatael/30 - g9hkH8v.gif',
    './interfaz/imagenes/Cards/Scoiatael/31 - lVjxO05.gif',
    './interfaz/imagenes/Cards/Scoiatael/32 - ikWlhNd.gif',
    './interfaz/imagenes/Cards/Scoiatael/33 - 2KMh7gd.gif',
    './interfaz/imagenes/Cards/Scoiatael/34 - sOrebfX.gif',
    './interfaz/imagenes/Cards/Scoiatael/35 - DdAWUG4.gif',
    './interfaz/imagenes/Cards/Scoiatael/36 - 7zDqkxq.gif',
    './interfaz/imagenes/Cards/Scoiatael/37 - 1XWigSF.gif',
    './interfaz/imagenes/Cards/Scoiatael/38 - gkdieTn.gif',
    './interfaz/imagenes/Cards/Scoiatael/39 - wl4eYhP.gif',
    './interfaz/imagenes/Cards/Scoiatael/4 - cqVjFh8.gif',
    './interfaz/imagenes/Cards/Scoiatael/40 - e0I5Smj.gif',
    './interfaz/imagenes/Cards/Scoiatael/41 - AQdLqjg.gif',
    './interfaz/imagenes/Cards/Scoiatael/42 - 4pjEODa.gif',
    './interfaz/imagenes/Cards/Scoiatael/43 - LxSZ6at.gif',
    './interfaz/imagenes/Cards/Scoiatael/44 - lCck1Wz.gif',
    './interfaz/imagenes/Cards/Scoiatael/45 - YhsrfVk.gif',
    './interfaz/imagenes/Cards/Scoiatael/46 - akyHwvO.gif',
    './interfaz/imagenes/Cards/Scoiatael/47 - LXZzaPS.gif',
    './interfaz/imagenes/Cards/Scoiatael/48 - zFBGp4n.gif',
    './interfaz/imagenes/Cards/Scoiatael/49 - bFhJHlr.gif',
    './interfaz/imagenes/Cards/Scoiatael/5 - I4WBnHJ.gif',
    './interfaz/imagenes/Cards/Scoiatael/50 - Cyh7KM7.gif',
    './interfaz/imagenes/Cards/Scoiatael/51 - huFZyMR.gif',
    './interfaz/imagenes/Cards/Scoiatael/6 - ybNWaC3.gif',
    './interfaz/imagenes/Cards/Scoiatael/7 - lxUscdG.gif',
    './interfaz/imagenes/Cards/Scoiatael/8 - OaGrJWi.gif',
    './interfaz/imagenes/Cards/Scoiatael/9 - BdQWnBa.gif',
    './interfaz/imagenes/Cards/Skellige/1 - nSAvZDY.gif',
    './interfaz/imagenes/Cards/Skellige/10 - DvOz4JC.gif',
    './interfaz/imagenes/Cards/Skellige/11 - B3UQKwm.gif',
    './interfaz/imagenes/Cards/Skellige/12 - YdHIxUD.gif',
    './interfaz/imagenes/Cards/Skellige/13 - LLs1n6I.gif',
    './interfaz/imagenes/Cards/Skellige/14 - RzZDuPg.gif',
    './interfaz/imagenes/Cards/Skellige/15 - ciCJlr7.gif',
    './interfaz/imagenes/Cards/Skellige/16 - aV2jHTz.gif',
    './interfaz/imagenes/Cards/Skellige/17 - v4GMkbf.gif',
    './interfaz/imagenes/Cards/Skellige/18 - qBfz13J.gif',
    './interfaz/imagenes/Cards/Skellige/19 - t4uLNjN.gif',
    './interfaz/imagenes/Cards/Skellige/2 - Qo2OtQN.gif',
    './interfaz/imagenes/Cards/Skellige/20 - dE5qlZS.gif',
    './interfaz/imagenes/Cards/Skellige/21 - jjoX9uZ.gif',
    './interfaz/imagenes/Cards/Skellige/22 - srr4Hqn.gif',
    './interfaz/imagenes/Cards/Skellige/23 - 1J5GTM9.gif',
    './interfaz/imagenes/Cards/Skellige/24 - LabdRLx.gif',
    './interfaz/imagenes/Cards/Skellige/25 - yZ9rOkJ.gif',
    './interfaz/imagenes/Cards/Skellige/26 - HoEgFtH.gif',
    './interfaz/imagenes/Cards/Skellige/27 - 6Eavv1n.gif',
    './interfaz/imagenes/Cards/Skellige/28 - Suz0fll.gif',
    './interfaz/imagenes/Cards/Skellige/29 - 8JFR0kG.gif',
    './interfaz/imagenes/Cards/Skellige/3 - rfbWLEn.gif',
    './interfaz/imagenes/Cards/Skellige/30 - fx7a11x.gif',
    './interfaz/imagenes/Cards/Skellige/31 - SFJyVyV.gif',
    './interfaz/imagenes/Cards/Skellige/32 - zlQ7aRt.gif',
    './interfaz/imagenes/Cards/Skellige/33 - ycJUdnZ.gif',
    './interfaz/imagenes/Cards/Skellige/34 - eqOqXTk.gif',
    './interfaz/imagenes/Cards/Skellige/35 - T2WomPC.gif',
    './interfaz/imagenes/Cards/Skellige/36 - 90bWqJN.gif',
    './interfaz/imagenes/Cards/Skellige/37 - lp70zLh.gif',
    './interfaz/imagenes/Cards/Skellige/38 - kAJ3dLp.gif',
    './interfaz/imagenes/Cards/Skellige/39 - eAczc3L.gif',
    './interfaz/imagenes/Cards/Skellige/4 - BwYsj1c.gif',
    './interfaz/imagenes/Cards/Skellige/40 - DbrlvbE.gif',
    './interfaz/imagenes/Cards/Skellige/41 - wwMTWLe.gif',
    './interfaz/imagenes/Cards/Skellige/42 - AMUGdqS.gif',
    './interfaz/imagenes/Cards/Skellige/43 - CpJBUew.gif',
    './interfaz/imagenes/Cards/Skellige/44 - RYH88E2.gif',
    './interfaz/imagenes/Cards/Skellige/45 - yPfYDeQ.gif',
    './interfaz/imagenes/Cards/Skellige/46 - JNdSnHd.gif',
    './interfaz/imagenes/Cards/Skellige/47 - gmYcJf1.gif',
    './interfaz/imagenes/Cards/Skellige/48 - nsqaKa6.gif',
    './interfaz/imagenes/Cards/Skellige/49 - eq7cCyr.gif',
    './interfaz/imagenes/Cards/Skellige/5 - Vx1pFmg.gif',
    './interfaz/imagenes/Cards/Skellige/50 - 9p72pO7.gif',
    './interfaz/imagenes/Cards/Skellige/51 - EMd8Kvd.gif',
    './interfaz/imagenes/Cards/Skellige/52 - UOqJrk9.gif',
    './interfaz/imagenes/Cards/Skellige/53 - UjleVJ6.gif',
    './interfaz/imagenes/Cards/Skellige/54 - iD8YzVx.gif',
    './interfaz/imagenes/Cards/Skellige/55 - 0iLQ969.gif',
    './interfaz/imagenes/Cards/Skellige/56 - xos9mKh.gif',
    './interfaz/imagenes/Cards/Skellige/6 - mYnJqXa.gif',
    './interfaz/imagenes/Cards/Skellige/7 - Kjc86Eo.gif',
    './interfaz/imagenes/Cards/Skellige/8 - cKIALOB.gif',
    './interfaz/imagenes/Cards/Skellige/9 - qwZvQsG.gif'
    


];

export default gifFiles;